registry/coder/README.md
The email is only for paying customers. Removing this will help us get random support requests.
=> chore: remove support email

CONTRIBUTING.md
- Revised the release process description for better clarity.
- Added detailed steps for creating and pushing annotated tags.
- Updated notes on version numbering and publishing to the Coder Registry.
=> chore: update CONTRIBUTING.md to replace incomplete release script with manual instruction.

registry/coder/modules/code-server/main.tf, registry/coder/modules/code-server/run.sh
Should resolve https://github.com/coder/registry/issues/27
The goal is to provide a method for template owners to configure default `Machine Settings` that can be overridden by developers via `User Settings` and repositories via `Workspace Settings`.
This option allows template owners to push new settings options with a template release that would not be ignored because the setting file already exists.
This also formats the `settings.json` file if `jq` is installed.
Eventually, I would imagine the current `settings` option will be depreciated in favor of this option.
=> feat(code-server): add machine settings option

registry/coder/modules/goose/README.md, registry/coder/modules/goose/main.tf
- Changed default values from null to empty strings for `experiment_goose_provider` and `experiment_goose_model` variables in main.tf to ensure compatibility and avoid null interpolation issues.
=> fix(coder/modules/goose): update default values for Goose provider and model variables to empty strings

registry/coder/modules/goose/README.md, registry/coder/modules/goose/main.tf
- Add Multiplexer, and tmux with mouse support.
- Add check to make sure tmux and screen are not set at the same time.
- Add Variable for session name so the name of the screen or tmux session can be customized.
Tested in dev environment.
Reference: https://github.com/coder/registry/issues/31
=> feat(goose): Add tmux support and Session Name variable to Goose

registry/coder/modules/claude-code/README.md
Let's be upfront about how our module works so operators/template authors can evaluate the security implications.
=> chore: add security notice for `--dangerously-skip-permissions` in Claude module

registry/coder/modules/claude-code/README.md, registry/coder/modules/claude-code/main.tf
- needed to install MCP servers
- workaround sucked
=> fix(claude-code): run post-install script after configuring MCP and remove `send-keys` workaround

registry/coder/modules/windows-rdp/README.md, registry/coder/modules/windows-rdp/powershell-installation-script.tftpl
Relates to 
Fixes an issue where RDP doesn't function properly over Coder Connect, by disabling UDP and relying only on TCP. c.f. https://github.com/coder/internal/issues/608#issuecomment-2965923672 for a detailed description of the problem.
---
---
**Path:** `registry/coder/modules/windows-rdp`  
**New version:** `v1.0.19`  
**Breaking change:** [ ] Yes [x] No
---
---
https://github.com/coder/internal/issues/608
Closes #
=> fix: disable UDP connections on windows-rdp module

.github/workflows/version-bump.yaml
update GitHub Actions permissions in version-bump workflow by adding issues permission for commenting on PR's
---
---
None
=> fix: update GitHub Actions permissions in version-bump workflow 

registry/coder/modules/claude-code/README.md, registry/coder/modules/claude-code/main.test.ts, registry/coder/modules/claude-code/main.tf, registry/coder/modules/claude-code/scripts/agentapi-start.sh, registry/coder/modules/claude-code/scripts/agentapi-wait-for-start.sh, registry/coder/modules/claude-code/scripts/remove-last-session-id.js, registry/coder/modules/claude-code/testdata/agentapi-mock.js, registry/coder/modules/claude-code/testdata/claude-mock.js, registry/coder/modules/claude-code/testdata/coder-mock.js, test/test.ts
Related to https://github.com/coder/internal/issues/700
This PR:
- makes AgentAPI a required dependency of the module. It's now used:
- to improve task reporting (by exporting `CODER_MCP_AI_AGENTAPI_URL` before running `coder exp mcp configure claude-code`)
- to add a web chat interface to Claude (using the `Claude Code Web` workspace app)
- removes support for tmux and screen since we don't need them if we have AgentAPI
- makes the Claude Code CLI workspace app optional and disabled by default - a new `experiment_cli_app` module variable controls its presence
- makes the module spawn the `coder_ai_task` resource, which makes the module compatible with the new Coder Tasks feature
- makes Claude Code remember the conversation between workspace restarts using the `--continue` flag. …
=> feat(modules/claude-code): make the module ready for Coder Tasks

.github/workflows/deploy-registry.yaml
Reverts https://github.com/coder/registry/pull/168 which should not have been merged, and disables production deployments for now until a fix is in place on the registry-server side.
=> fix: disable production deployments from main

.github/workflows/deploy-registry.yaml
This PR updates the CI release flow to match the registry-server's new development flow.
The "dev" registry now deploys directly from the main branch of registry-server.
The "production" registry now deploys from tagged releases of registry-server. We have added a "production" tag that will
track the same commit as the latest semver release of the registry-server.
---
---
Fixes https://github.com/coder/registry/pull/170
Closes #
=> fix: update release action to match new registry-server dev flow

registry/coder/modules/jetbrains-gateway/README.md, registry/coder/modules/jetbrains-gateway/main.test.ts, registry/coder/modules/jetbrains-gateway/main.tf
This PR adds the agent_id parameter to the url so jetbrains-gateway can handle multiple agents.
---
---
---
Closes #166
=> fix(jetbrains-gateway) add agent id to url

registry/coder-labs/templates/tasks-docker/README.md
This PR updates the `maintainer_github` field for the new Coder Labs template to use the value of `coder-labs`. This shouldn't be necessary (`maintainer_github` should be deprecated), but something is off with our build step.
---
None
=> fix: update namespace for coder-labs template

CONTRIBUTING.md
Add contributing guide for new and existing templates
---
=> docs(CONTRIBUTING): add template contributing guide for new and existing templates

registry/coder/modules/agentapi/README.md, registry/coder/modules/agentapi/main.test.ts, registry/coder/modules/agentapi/main.tf, registry/coder/modules/agentapi/scripts/agentapi-wait-for-start.sh, registry/coder/modules/agentapi/scripts/main.sh, registry/coder/modules/agentapi/test-util.ts, registry/coder/modules/agentapi/testdata/agentapi-mock.js, registry/coder/modules/agentapi/testdata/agentapi-start.sh, registry/coder/modules/agentapi/testdata/ai-agent-mock.js, test/test.ts
The agentapi module is a building block for modules that need to run an agentapi server. It's not meant for end users of Coder.
The agentapi-specific logic is mostly extracted from [the claude-code module](https://github.com/coder/registry/tree/c0f2d945c5808c1962b15b5c2e2a5269ea0f4339/registry/coder/modules/claude-code). You can see this module in action in [the goose 2.0 PR](https://github.com/coder/registry/pull/178).
=> feat: add the agentapi module

registry/coder/modules/claude-code/README.md, registry/coder/modules/claude-code/main.tf
Spotted here: https://github.com/coder/coder/pull/18988 
This PR bumps up the default version of agentapi to support Mac arm64 users.
**Path:** `registry/coder/modules/claude-code`  
**New version:** no?
**Breaking change:** No
=> chore: bump agentapi version to v0.2.3

registry/coder/modules/jupyter-notebook/README.md, registry/coder/modules/jupyter-notebook/main.tf, registry/coder/modules/jupyter-notebook/run.sh
Preinstall Python packages for Jupyter Notebook projects.
**Path:** `registry/coder/modules/jupyter-notebook`  
**New version:** `v1.2.0`  
**Breaking change:** [ ] Yes [x] No
```tf
module "jupyter-notebook" {
count    = data.coder_workspace.me.start_count
source   = "git::https://github.com/coder/registry.git//registry/coder/modules/jupyter-notebook?ref=feat-jupyter-packages"
agent_id = coder_agent.main.id
pip_install_extra_packages = "numpy==1.26.4 django"
}
```
=> feat: jupyter-notebook: preinstall Python packages

registry/coder/modules/hcp-vault-secrets/README.md
Realized this was an issue while fixing how we're rendering GFM alerts on the Registry website.
Basically, the URLs we're using right now are technically valid, but they were using the old URL pattern from before we created the `coder/registry` repo. The Registry website has logic to handle redirects for these, but we should avoid triggering it as it adds unnecessary entries to the user's browser history.
- Updated all Registry links in the HCP Vault alert to include `coder` as the namespace
=> fix: update HCP vault links to use current URL patterns

registry/coder/modules/claude-code/README.md, registry/coder/modules/claude-code/main.tf
Workaround to address https://github.com/coder/coder/issues/18776
=> fix(claude-code): workaround for a coder bug

registry/coder/modules/claude-code/README.md, registry/coder/modules/claude-code/main.tf
The workaround introduced in https://github.com/coder/registry/pull/283 sometimes causes Coder to associate the Coder agent with the `terraform_data` resource instead of a compute resource. Additionally, it creates a new agent once a workspace is stopped.
See https://codercom.slack.com/archives/C08PHACTZRB/p1754391012982629 for more details.
Related to https://github.com/coder/coder/issues/18776.
=> fix(claude-code): revert workaround

registry/coder/modules/jetbrains/README.md, registry/coder/modules/jetbrains/main.tf
This PR adds a description field to the `jetbrains_ides` `coder_parameter`.
This allows the JetBrains IDEs parameter to display a helpful description in both the Coder UI and the CLI, improving clarity for users when selecting which IDEs to configure in a workspace.
https://github.com/coder/coder/issues/19145
=> chore: add description to JetBrains IDEs parameter

registry/coder-labs/modules/gemini/README.md, registry/coder-labs/modules/gemini/main.tf, registry/coder/modules/goose/README.md, registry/coder/modules/goose/main.tf
related to https://github.com/coder/registry/pull/320
=> chore: bump agentapi versions in the goose and gemini modules

registry/coder/modules/jetbrains/README.md
Patch version bump to 1.0.3 since it was missed in last PR.
**Path:** `registry/coder/modules/jetbrains`  
**New version:** `v1.0.3`  
None
=> chore(jetbrains): version bump to 1.0.3

scripts/tag_release.sh
```console
🚀 Coder Registry Tag Release Script
Operating on commit: 4238f38353a20c52afc28de8a3878b029a7473c2
🔍 Scanning all modules for missing release tags...
⚠️  anomaly/.coder: No version found in README, skipping
✅ anomaly/tmux: v1.0.0 (already tagged)
⚠️  coder-labs/.coder: No version found in README, skipping
✅ coder-labs/cursor-cli: v0.1.1 (already tagged)
✅ coder-labs/gemini: v1.1.0 (already tagged)
⚠️  coder-labs/jetbrains-fleet: No version found in README, skipping
⚠️  coder/.coder: No version found in README, skipping
✅ coder/agentapi: v1.1.1 (already tagged)
✅ coder/aider: v1.1.2 (already tagged)
✅ coder/amazon-dcv-windows: v1.1.1 (already tagged)
✅ coder/amazon-q: v1.1.2 (already tagged)
✅ coder/aws-region: v1.0.31 (already tagged)
✅ coder/azure-region: v1.0.31 (already …
```
=> chore: fix module detection to exclude hidden dirs

registry/coder-labs/templates/tasks-docker/main.tf
I don't know how long this was broken for, but we had a [customer run into this](https://codercom.slack.com/archives/C04EHNF3A0Y/p1755635729486939). I also noticed that the MCP seemed to still report "ok" when this was reported with the wrong slug. Ultimately, I'm not sure if this should even be in our example template or if it should be in the module itself, or if its needed at all. Perhaps @35C4n0r, @matifali, or @DevelopmentCats has thoughts on how we can improve this UX overall.
=> fix: use correct app slug for status reporting

.github/workflows/release.yml
CI was failing on new module releases because there was no fallback to gh api failures when there was no previous tag for the module was found.
https://github.com/coder/registry/actions/runs/17225186737/job/48868318539
=> fix(ci): add fallback for GitHub API failures in release workflow

registry/coder/modules/claude-code/README.md, registry/coder/modules/claude-code/main.tf
Closes #
- Introduces `subdomain` variable
- Logic for subdomain and base path
Tested with and without subdomain to ensure no breaking changes
**Path:** `registry/coder/modules/claude-code`  
**New version:** `v2.2.0`  
**Breaking change:** [X] Yes [ ] No
=> feat(claude-code): add subdomain variable and logic

registry/coder/modules/cursor/README.md, registry/coder/modules/cursor/main.tf, registry/coder/modules/kiro/README.md, registry/coder/modules/kiro/main.test.ts, registry/coder/modules/kiro/main.tf, registry/coder/modules/windsurf/README.md, registry/coder/modules/windsurf/main.test.ts, registry/coder/modules/windsurf/main.tf
- Introduces mcp file creation via `coder_script` in kiro and windsurf modules
- Add mcp variable to both modules
- Add slug and display_name variables to windsurf to match up with other modules 
- Add tests for testing mcp file creation for both kiro and windsurf
**Path:** `registry/coder/modules/kiro`  
**New version:** `v1.1.0`  
**Path:** `registry/coder/modules/windsurf`  
**New version:** `v1.2.0`  
**Path:** `registry/coder/modules/cursor`  
**New version:** `v1.3.2`  
=> feat: add mcp config for kiro and windsurf modules

cmd/readmevalidation/codermodules.go, cmd/readmevalidation/coderresources.go, cmd/readmevalidation/codertemplates.go, registry/coder/templates/azure-linux/README.md, registry/coder/templates/azure-windows/README.md
No issue to link – this was a problem we discovered while updating the Registry website
This PR adds (very) basic validation for the GitHub Flavored Markdown alerts that we allow contributors to add to their README files. The errors that get generated should be correct, but the error messages themselves aren't as helpful as they could be. I'm going to be handling that in a separate PR, just so we can get this one in sooner.
- Added function for validating the core structure of all GFM alerts
- Updated existing README files that were failing the new validation requirements
=> fix: add validation for Github-Flavored Markdown Alerts

registry/coder/modules/jfrog-oauth/README.md, registry/coder/modules/jfrog-oauth/conda.conf.tftpl, registry/coder/modules/jfrog-oauth/main.test.ts, registry/coder/modules/jfrog-oauth/main.tf, registry/coder/modules/jfrog-oauth/run.sh, registry/coder/modules/jfrog-token/README.md, registry/coder/modules/jfrog-token/conda.conf.tftpl, registry/coder/modules/jfrog-token/main.test.ts, registry/coder/modules/jfrog-token/main.tf, registry/coder/modules/jfrog-token/run.sh
Closes #34 
Jfrog Modules doesn't support conda package manager, This PR adds support of that
#34 
/claim #34
=> feat: add conda support to JFrog modules

registry/coder/modules/jfrog-oauth/README.md, registry/coder/modules/jfrog-oauth/main.test.ts, registry/coder/modules/jfrog-oauth/main.tf, registry/coder/modules/jfrog-oauth/run.sh, registry/coder/modules/jfrog-oauth/settings.xml.tftpl, registry/coder/modules/jfrog-token/README.md, registry/coder/modules/jfrog-token/main.test.ts, registry/coder/modules/jfrog-token/main.tf, registry/coder/modules/jfrog-token/run.sh, registry/coder/modules/jfrog-token/settings.xml.tftpl
Closes #33 
/claim #33 
Jfrog Modules doesn't support conda package manager, This PR adds support of that
#33 
https://github.com/user-attachments/assets/61c33963-e1a7-43e2-b1cc-fdb747405cf5
=> Add maven package manager support to JFrog modules

registry/coder/modules/jetbrains-gateway/README.md, registry/coder/modules/jetbrains-gateway/main.test.ts, registry/coder/modules/jetbrains-gateway/main.tf
Fixes a regression added in #167 which implemented support for multiple agents by appending the agent id to the URI, however in a single agent environment it results in the agent id from the template apply (on upload to Coder from client) being injected, and when a workspace is later built using the template the agent id is no longer correct.
Resolves the error `The workspace “<name>” does not have an agent with ID “<id>”` being thrown by Jetbrains Gateway app upon attempting to open a Jetbrains app from within a Coder workspace.
When wishing to target a specific Coder Agent with the Jetbrains Gateway module one should use the `agent_name` variable in the module configuration to specify the desired agent name. This will append the agent name to the URI.
**Path:** …
=> chore: fix for jetbrains gateway agent_id issue

CONTRIBUTING.md, README.md
Add links to `MAINTAINER.md` in `README.md` and `CONTRIBUTING.md` to help guide internal contributors.
=> docs: add MAINTAINER.md link to CONTRIBUTING.md and README.md

registry/coder/modules/claude-code/README.md, registry/coder/modules/claude-code/scripts/install.sh, registry/coder/modules/claude-code/scripts/start.sh
Closes #458
It only sources the bashrc file if it exists (as the startup/install scripts will fail if the workspace doesn't have that)
**Path:** `registry/coder/modules/claude-code`  
**New version:** `v3.0.2`   <--- Maintainers, I'll have to lookup how to bump this for this project
**Breaking change:** [ ] Yes [x] No
=> fix(claude-code): source bashrc file only if it exists

registry/coder-labs/modules/copilot/README.md, registry/coder-labs/modules/copilot/main.tf, registry/coder-labs/modules/copilot/scripts/install.sh, registry/coder-labs/modules/copilot/scripts/start.sh
Closes #462
Fixes missing COPILOT_MODEL arg from install script
**Path:** `registry/coder-labs/modules/copilot`  
**New version:** `v0.1.1`  
=> fix: Add COPILOT_MODEL to install script args

registry/coder-labs/modules/copilot/README.md
update display name for copilot module to Copilot CLI
**Path:** `registry/coder-labs/modules/copilot`  
**New version:** `v0.1.2`  
=> chore: update display name for copilot module to Copilot CLI

registry/coder/modules/git-clone/README.md
Changes `coder_git_auth` to `coder_external_auth` in README
**Path:** `registry/coder/modules/git-clone` 
**New version:** `v1.1.2`  
=> fix(git-clone): Update README.md
